name: Build Main

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Build Plastic
      run: dotnet build src/Plastic/Plastic.csproj -c Release
      
    - name: Test 
      run: dotnet test tests/Plastic.UnitTests/Plastic.UnitTests.csproj -c Release --no-build

    - name: Test (internal)
      run: dotnet test tests/Plastic.UnitTests.Internal/Plastic.UnitTests.Internal.csproj -c Release --no-build
        
    - name: Publish Package to Nuget.org
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NugetApiKey }} --source "nuget.org" --skip-duplicate --no-symbols true
